#固定链接格式
permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown
#产生相关帖子的索引
lsi: true
#允许Pygments处理代码语法高亮
pygments: true
kramdown:
  input: GFM

# 作者信息
author: 
  name: 谭礼渊
  email: undefined4me@gmail.com
  link: http://tanliyuan.github.io
  weibo: 
  github: http://github.com/tanliyuan 

# 站点信息
title: 谭礼渊的博客 
description: 谭礼渊的博客
url: http://tanliyuan.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yansu-uploads.stor.sinaapp.com/imgs/gavatar.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-57264441-1
  url: auto

# disqus 设置
disqus:
  shortname: tanliyuan

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Javascript
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
